name: CppCheck

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: cppcheck
      uses: deep5050/cppcheck-action@a4dcbb4f03f99ac4fbe141dbefd199ff64fc4622 # main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
