name: Luacheck

on: [push, pull_request]

permissions:
  contents: read

jobs:

  luacheck:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install Packages
      run: sudo apt update; sudo apt install -y lua5.3 lua-check

    - name: Run ‘luacheck’ linter
      run: luacheck examples
