name: Luacheck

on: [push, pull_request]

permissions:
  contents: read

jobs:

  luacheck:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Install Packages
      run: sudo apt update; sudo apt install -y lua5.3 lua-check

    - name: Run ‘luacheck’ linter
      run: luacheck examples
